name: 'Prepare Cluster'
description: 'Prepare Cluster'
inputs:
  app-slug:
    description: 'App Slug.'
    required: true
    default: ''
  api-token:
    description: 'API Token.'
    required: true
    default: ''
  chart:
    description: 'Path to the helm chart (One of `chart` or `yaml-dir` is required).'
    required: false
  yaml-dir:
    description: 'The directory containing multiple yamls for a Replicated release.'
    required: false
  kubernetes-distribution:
    description: 'Kubernetes distribution of the cluster to provision.'
    required: true
  kubernetes-version:
    description: 'Kubernetes version to provision (format is distribution dependent).'
    required: false
  cluster-name:
    description: 'Name of the cluster to provision'
    required: false
    default: ''
  ttl:
    description: 'Cluster TTL (duration, max 48h)'
    required: false
  disk:
    description: 'Disk size in GiB'
    required: false
  nodes:
    description: 'Number of nodes to provision'
    required: false
  min-nodes:
    description: 'Minimum number of nodes to provision'
    required: false
  max-nodes:
    description: 'Maximum number of nodes to provision'
    required: false
  instance-type:
    description: 'Instance type to provision'
    required: false
  timeout-minutes:
    description: 'Time to wait for the cluster to have a status of `running`'
    required: false
    default: '20'
  node-groups:
    description: |
      Node groups to provision.
      Example:
      <pre>node-groups: \|
        - name: "worker"
          instance-type: "t3.medium"
          disk: 100
          nodes: 3</pre>
    required: false
  tags:
    description: |
      Tags to assign to the cluster.
      Example:
      <pre>tags: \|
        - key: "department"
          value: "engineering"</pre>
    required: false
  kubeconfig-path:
    description: 'If specified, the kubeconfig will be written to this path'
    required: false
  export-kubeconfig:
    description: 'Export the KUBECONFIG variable (true/false)'
    required: false
    default: 'false'
  helm-values:
    description: 'A Helm values.yaml file to use'
    required: false
  helm-chart-name:
    description: 'The name of the Helm chart to use'
    required: false
  helm-run-preflights:
    description: 'Run preflight checks (true/false)'
    required: false
    default: 'true'
  kots-config-values:
    description: 'The KOTS config values to use'
    required: false
  kots-wait-duration:
    description: 'Timeout for KOTS to be used while waiting for individual components to be ready. must be in Go duration format (eg: 10s, 2m) (default "2m")'
    required: false
  customer-entitlements:
    description: |
      Entitlements to assign to the customer.
      Example:
      <pre>customer-entitlements: \|
        - name: "number-of-users"
          value: "10"</pre>
    required: false
outputs:
  cluster-id: # id of the cluster
    description: 'Contains the cluster id.'
    value: ${{ steps.create-cluster.outputs.cluster-id }}
  cluster-kubeconfig: # kubeconfig of the cluster
    description: 'Contains the kubeconfig to connect with the cluster.'
    value: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
runs:
  using: "composite"
  steps:
  - name: 'Create Release'
    id: 'create-release'
    uses: ./create-release
    with:
      app-slug: ${{ inputs.app-slug }}
      api-token: ${{ inputs.api-token }}
      yaml-dir: ${{ inputs.yaml-dir }}
      chart: ${{ inputs.chart }} 
  - name: 'Create Customer'
    id: 'create-customer'
    uses: ./create-customer
    with:
      app-slug: ${{ inputs.app-slug }}
      api-token: ${{ inputs.api-token }}
      customer-name: ${{ github.ref_name }}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}
      customer-email: ${{ github.ref_name }}@example.com
      license-type: "test"
      entitlements: ${{ inputs.customer-entitlements }}
      channel-slug: ${{ steps.create-release.outputs.channel-slug }}
  - name: Create Cluster
    id: create-cluster
    uses: ./create-cluster
    with:
      api-token: ${{ inputs.api-token }}
      kubernetes-distribution: ${{ inputs.kubernetes-distribution }}
      kubernetes-version: ${{ inputs.kubernetes-version }}
      cluster-name: ${{ inputs.cluster-name || format('{0}-{1}-{2}', github.ref_name, inputs.kubernetes-distribution, inputs.kubernetes-version) }}
      ttl: ${{ inputs.ttl || '' }}
      disk: ${{ inputs.disk || '' }}
      nodes: ${{ inputs.nodes || '' }}
      min-nodes: ${{ inputs.min-nodes || '' }}
      max-nodes: ${{ inputs.max-nodes || '' }}
      instance-type: ${{ inputs.instance-type || '' }}
      timeout-minutes: ${{ inputs.timeout-minutes || 20 }}
      node-groups: ${{ inputs.node-groups || '' }}
      tags: ${{ inputs.tags || '' }}
      kubeconfig-path: ${{ inputs.kubeconfig-path || '' }}
      export-kubeconfig: ${{ inputs.export-kubeconfig || false }}
  - name: Deploy the app with Helm
    uses: ./helm-install
    if: ${{ inputs.chart != '' }}
    with:
      kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
      helm-path: "helm"
      registry-username: ${{ github.ref_name }}@example.com
      registry-password: ${{ steps.create-customer.outputs.license-id }}
      chart: oci://registry.replicated.com/${{ inputs.app-slug }}/release__${{ steps.create-release.outputs.release-sequence }}/${{ inputs.helm-chart-name }}
      name: ${{ inputs.app-slug }}
      namespace: 'default'
      values: ${{ inputs.helm-values }}
      run-preflights: ${{ inputs.helm-run-preflights }}
  - name: Deploy the app with KOTS
    if: ${{ inputs.yaml-dir != '' }}
    uses: ./kots-install 
    with:
      kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
      app-slug: ${{ inputs.app-slug }}/test-channel
      license-file: ${{ steps.create-customer.outputs.license-file }}
      app-version-label: release__${{ steps.create-release.outputs.release-sequence }}
      config-values: ${{ inputs.kots-config-values }}
      wait-duration: ${{ inputs.kots-wait-duration }}
