name: "Create Channel"
description: "Create a channel"
inputs:
  api-token:
    description: "API Token."
    required: true
  app-slug:
    description: "App Slug."
    required: true
  channel-name:
    description: "The name of the channel to create."
    required: true
  build-airgap-automatically:
    description: "Build airgap bundles automatically for releases promoted to this channel."
    required: false
    default: "false"
outputs:
  channel-id:
    description: "Contains the channel id."
  channel-slug:
    description: "Contains the channel slug."
runs:
  using: "node24"
  main: "index.js"
