name: "Promote Release"
description: "Promote a Release to a Channel"
inputs:
  app-slug:
    description: "App Slug."
    required: true
  api-token:
    description: "API Token."
    required: true
  channel-to:
    description: "The slug of the Channel to promote the release sequence to."
    required: true
  release-sequence:
    description: "The release sequence number to promote."
    required: true
  release-version:
    description: "The version field of the Release to promote."
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
