name: "Get VM SSH Endpoint"
description: "Get the SSH endpoint for a VM"
inputs:
  api-token:
    description: "API Token."
    required: true
  vm-id:
    description: "The ID of the VM to get the SSH endpoint for."
    required: true
  username:
    description: "Optional username to include in the SSH endpoint."
    required: false
outputs:
  ssh-endpoint:
    description: "Contains the SSH endpoint for the VM."
runs:
  using: "node24"
  main: "index.js"
